#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Nov 19 13:35:34 2019

@author: davinpc
"""

degrees = 120
radians = degrees * 3.14 / 180
print(degrees)
print(radians)


student1 = 80
student2 = 90
student3 = 95
average = (student1 + student2 + student3) / 3
print(student1)
print(student2)
print(student3)
print(average)


class1 = 32 // 5
class2 = 45 // 7
class3 = 51 // 6
print(class1)
print(class2)
print(class3)
leftover_class1 = 32 - (class1*5)
leftover_class2 = 45 - (class2*7)
leftover_class3 = 51 - (class3*6)
print(leftover_class1)
print(leftover_class2)
print(leftover_class3)


pi = 3.14
pie_diameter = 55.4
pie_radius = pie_diameter / 2
circumference = 2 * pi * pie_radius
circumference_msg = "Jimmy's pie has a circumference: "
print(circumference_msg, circumference)


velocity = 514
frequency = 256
wavelength = velocity/frequency
print(velocity)
print(frequency)
print(wavelength)
